version: "3.3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - "./src:/app/src"
      - "./flask_db.sh:/app/src/flask_db.sh"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
networks:
  default:
    external:
      name: pi2-esteira-network
