"""empty message

Revision ID: 3c1169262371
Revises: b14e551dea48
Create Date: 2022-04-21 19:06:43.537945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1169262371'
down_revision = 'b14e551dea48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
