"""empty message

Revision ID: 433854bb311e
Revises: 70ca8649b16d
Create Date: 2022-04-22 20:29:26.423612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433854bb311e'
down_revision = '70ca8649b16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sucess', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('placas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sucesso', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='placas_pkey')
    )
    op.drop_table('boards')
    # ### end Alembic commands ###
