"""empty message

Revision ID: 982cde0e54a8
Revises: 433854bb311e
Create Date: 2022-04-22 20:31:24.048407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982cde0e54a8'
down_revision = '433854bb311e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('tags', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
